server:
    port: 8081
    application:
        name: community-api
    servlet:
        context-path: /api

spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:file:./database/community
        username: sa
        password:
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher