server:
    port: 8080
    application:
        name: community-api
    servlet:
        context-path: /api

spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:testdb
        username: community
        password:
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher